# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1


jobs:
  install-dependencies:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: 
          name: 'ls'
          command: 'ls -l'
      - node/install-packages
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint-application:
    steps:
      - run: 
          name: 'ls'
          command: 'ls -l'
      - run:
          name: 'Lint application'
          command: 'npm run lint'
  setup-env:
    steps: 
      - run:
          name: Setup environment variables
          command: echo 'export NODE_ENV="TEST"' >> $BASH_ENV
  unit-test:
    steps:
      - run:
          name: 'Unit test'
          command: 'npm test'

workflows:
  commit: 
    jobs:
      - install-dependencies
      - setup-env:
          requires:
            - install-dependencies
      - lint-application:
          requires:
            - setup-env
      - unit-test:
          requires:
            - lint-application
