version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  install-dependencies:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint-application:
    docker:
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Lint application'
          command: 'npm run lint'
      - persist_to_workspace:
          root: .
          paths:
            - .

  setup-env:
    docker:
      - image: cimg/node:15.1
    steps: 
      - attach_workspace:
          at: .
      - run:
          name: Setup environment variables
          command: echo 'export NODE_ENV="TEST"' >> $BASH_ENV
      - persist_to_workspace:
          root: .
          paths:
            - .

  unit-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'tell me what env'
          command: 'echo $BASH_ENV'
      - run:
          name: 'Unit test'
          command: 'npm test'

workflows:
  commit: 
    jobs:
      - install-dependencies
      - setup-env:
          requires:
            - install-dependencies
      - lint-application:
          requires:
            - setup-env
      - unit-test:
          requires:
            - lint-application
