import { PlaceResponse, TextbeltResponse } from '../src/types';

export const mockPlaceResponse: PlaceResponse = {
  Message: "Built in 19.5356 ms size 32833 bytes",
  SelectedPlaceId: 720,
  HighlightedPlaceId: 0,
  Latitude: 0.0,
  Longitude: 0.0,
  StartDate: "2021-05-31",
  EndDate: "2021-05-31",
  CountNearby: true,
  NearbyLimit: 100,
  Sort: "Distance",
  CustomerId: null,
  Filters: {
    IsADA: "False",
    UnitCategoryId: "0",
    SleepingUnitId: "0",
    MinVehicleLength: "0",
  },
  AvailablePlaces: 12,
  SelectedPlace: {
    PlaceId: 720,
    Name: "South Carlsbad SB",
    Description:
      "This San Diego beach features swimming, surfing, skin diving, fishing and picnicking. The large blufftop campground is very popular, especially in summer. Stairs lead to the beach.",
    HasAlerts: true,
    IsFavourite: false,
    Allhighlights:
      "Bicycling<br>Boating<br>Body surfing<br>Camping<br>Fishing<br>Group Camping<br>Picnic area<br>Rinse Showers<br>Scuba diving<br>Store-convenience<br>Surfing<br>Swimming<br>",
    Url: "http://www.parks.ca.gov/?page_id=660",
    ImageUrl:
      "https://cali-content.usedirect.com/Images/California/ParkImages/Place/720.jpg",
    BannerUrl:
      "https://cali-content.usedirect.com/Images/California/ParkImages/banner.jpg",
    ParkSize: "Medium",
    Latitude: 33.10165866,
    Longitude: -117.3186303,
    MilesFromSelected: 0,
    Available: false,
    AvailableFiltered: false,
    ParkCategoryId: 2,
    ParkActivity: 3,
    ParkPopularity: 0,
    AvailableUnitCount: 0,
    Restrictions: {
      FutureBookingStarts: "2021-05-31T00:00:00-07:00",
      FutureBookingEnds: "2021-11-29T00:00:00-08:00",
      MinimumStay: 1,
      MaximumStay: 7,
      IsRestrictionValid: true,
    },
    Facilities: {
      "708": {
        FacilityId: 708,
        Name: "Northern End (sites 1-34, 103-130)",
        Description: "Northern End (sites 1-34, 103-130)",
        RateMessage: null,
        FacilityType: 2,
        FacilityTypeNew: 1,
        InSeason: true,
        Available: false,
        AvailableFiltered: false,
        Restrictions: {
          FutureBookingStarts: "2021-05-31T00:00:00-07:00",
          FutureBookingEnds: "2021-11-29T00:00:00-08:00",
          MinimumStay: 1,
          MaximumStay: 30,
          IsRestrictionValid: true,
        },
        Latitude: 33.111996,
        Longitude: -117.323108,
        Category: "Campgrounds",
        EnableCheckOccupancy: false,
        AvailableOccupancy: null,
        FacilityAllowWebBooking: true,
        UnitTypes: {
          "4427": {
            UnitTypeId: 4427,
            Name: "Premium Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1,
            UnitTypeGroupId: 1,
            MaxVehicleLength: 35,
            HasAda: true,
            Restrictions: null,
            AvailableCount: 0,
          },
          "4303": {
            UnitTypeId: 4303,
            Name: "Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1,
            UnitTypeGroupId: 1,
            MaxVehicleLength: 35,
            HasAda: true,
            Restrictions: null,
            AvailableCount: 0,
          },
        },
      },
      "712": {
        FacilityId: 712,
        Name: "Southern End (sites 153-187)",
        Description: "Southern End (sites 153-187)",
        RateMessage: null,
        FacilityType: 2,
        FacilityTypeNew: 1,
        InSeason: true,
        Available: false,
        AvailableFiltered: false,
        Restrictions: {
          FutureBookingStarts: "2021-05-31T00:00:00-07:00",
          FutureBookingEnds: "2021-11-29T00:00:00-08:00",
          MinimumStay: 1,
          MaximumStay: 30,
          IsRestrictionValid: true,
        },
        Latitude: 33.091988,
        Longitude: -117.314656,
        Category: "Campgrounds",
        EnableCheckOccupancy: false,
        AvailableOccupancy: null,
        FacilityAllowWebBooking: true,
        UnitTypes: {
          "4427": {
            UnitTypeId: 4427,
            Name: "Premium Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1,
            UnitTypeGroupId: 1,
            MaxVehicleLength: 35,
            HasAda: true,
            Restrictions: null,
            AvailableCount: 0,
          },
        },
      },
      "714": {
        FacilityId: 714,
        Name: "Southern End (sites 131-152, 188-223)",
        Description: "Southern End (sites 131-152, 188-223)",
        RateMessage: null,
        FacilityType: 2,
        FacilityTypeNew: 1,
        InSeason: true,
        Available: false,
        AvailableFiltered: false,
        Restrictions: {
          FutureBookingStarts: "2021-05-31T00:00:00-07:00",
          FutureBookingEnds: "2021-11-29T00:00:00-08:00",
          MinimumStay: 1,
          MaximumStay: 30,
          IsRestrictionValid: true,
        },
        Latitude: 33.09775,
        Longitude: -117.317231,
        Category: "Campgrounds",
        EnableCheckOccupancy: false,
        AvailableOccupancy: null,
        FacilityAllowWebBooking: true,
        UnitTypes: {
          "4440": {
            UnitTypeId: 4440,
            Name: "Premium Double Hook Up (E/W/S) Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1015,
            UnitTypeGroupId: 20,
            MaxVehicleLength: 35,
            HasAda: true,
            Restrictions: null,
            AvailableCount: 0,
          },
          "4324": {
            UnitTypeId: 4324,
            Name: "Hook Up (E/W/S) Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1015,
            UnitTypeGroupId: 18,
            MaxVehicleLength: 35,
            HasAda: true,
            Restrictions: null,
            AvailableCount: 0,
          },
          "4427": {
            UnitTypeId: 4427,
            Name: "Premium Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1,
            UnitTypeGroupId: 1,
            MaxVehicleLength: 35,
            HasAda: false,
            Restrictions: null,
            AvailableCount: 0,
          },
          "4303": {
            UnitTypeId: 4303,
            Name: "Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1,
            UnitTypeGroupId: 1,
            MaxVehicleLength: 35,
            HasAda: true,
            Restrictions: null,
            AvailableCount: 0,
          },
        },
      },
      "715": {
        FacilityId: 715,
        Name: "Northern End (sites 35-102)",
        Description: "Northern End (sites 35-102)",
        RateMessage: null,
        FacilityType: 2,
        FacilityTypeNew: 1,
        InSeason: true,
        Available: false,
        AvailableFiltered: false,
        Restrictions: {
          FutureBookingStarts: "2021-05-31T00:00:00-07:00",
          FutureBookingEnds: "2021-11-29T00:00:00-08:00",
          MinimumStay: 1,
          MaximumStay: 30,
          IsRestrictionValid: true,
        },
        Latitude: 33.105192,
        Longitude: -117.320353,
        Category: "Campgrounds",
        EnableCheckOccupancy: false,
        AvailableOccupancy: null,
        FacilityAllowWebBooking: true,
        UnitTypes: {
          "4427": {
            UnitTypeId: 4427,
            Name: "Premium Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1,
            UnitTypeGroupId: 1,
            MaxVehicleLength: 35,
            HasAda: false,
            Restrictions: null,
            AvailableCount: 0,
          },
          "4303": {
            UnitTypeId: 4303,
            Name: "Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 1,
            UnitTypeGroupId: 1,
            MaxVehicleLength: 35,
            HasAda: true,
            Restrictions: null,
            AvailableCount: 0,
          },
        },
      },
      "2100": {
        FacilityId: 2100,
        Name: "North Loop (Group site)",
        Description: "North Loop (sites 1-130)",
        RateMessage: null,
        FacilityType: 2,
        FacilityTypeNew: 1,
        InSeason: true,
        Available: false,
        AvailableFiltered: false,
        Restrictions: {
          FutureBookingStarts: "2021-05-31T00:00:00-07:00",
          FutureBookingEnds: "2021-11-29T00:00:00-08:00",
          MinimumStay: 1,
          MaximumStay: 30,
          IsRestrictionValid: true,
        },
        Latitude: 33.105192,
        Longitude: -117.320353,
        Category: "Campgrounds",
        EnableCheckOccupancy: false,
        AvailableOccupancy: null,
        FacilityAllowWebBooking: true,
        UnitTypes: {
          "4436": {
            UnitTypeId: 4436,
            Name: "Premium Group Campsite",
            Available: false,
            AvailableFiltered: false,
            UnitCategoryId: 2,
            UnitTypeGroupId: 3,
            MaxVehicleLength: 35,
            HasAda: false,
            Restrictions: null,
            AvailableCount: 0,
          },
        },
      },
    },
  },
  NearbyPlaces: [],
};

export const mockTextbeltResponse: TextbeltResponse = {
  quotaRemaining: 50,
  success: true,
  textId: "0",
};